alias ..='cd ../'
alias ...='cd ../..'
alias cd..='cd ..'
alias cls='clear'
alias spe='cd ~/reposam/spe'
alias ssp='cd ~/reposam/ssp'
alias cdtmp='cd ~/tmp'
alias cdwork='[ -f ~/.config/.cdwork ] && cd $(cat ~/.config/.cdwork) || cd ~/work'

# git
alias groot='cd $(git rev-parse --show-toplevel)'
