alias ..='cd ../'
alias ...='cd ../..'
alias cd..='cd ..'
alias cls='clear'
alias llh='ls -lah'
alias spe='cd ~/reposam/spe'
alias ssp='cd ~/reposam/ssp'
alias cdtmp='cd ~/tmp'
alias cdwork='[ -f ~/.config/.cdwork ] && cd $(cat ~/.config/.cdwork) || cd ~/work'

alias pushdd="pushd \$PWD > /dev/null"
alias popdd='popd >/dev/null'
alias dirss='dirs -v'

# git
alias groot='cd $(git rev-parse --show-toplevel)'
