#!/bin/bash
tool=docker
if [ -z "${1}" ]; then
  echo ${tool} ps -a
  ${tool} ps -a
  echo
  echo ${tool} image ls
  ${tool} image ls
else
  echo ${tool} container inspect $@
  ${tool} container inspect $@
fi
