#!/bin/bash
ME=$(basename $0)
tool=docker

function usage() {
    echo "Usage: ${ME} [Container_ID] [Command]"
    echo "example:"
    echo "    ${ME} 123456789012 uname -a"
    exit 1
}

if [ -z "${1}" ]; then
    usage
fi

if [ -z "${2}" ]; then
    usage
fi

ctrid=${1}


echo ${tool} exec -t ${ctrid} "${@:2}"
${tool} exec -t ${ctrid} "${@:2}"
