#!/bin/bash
ME=$(basename $0)
tool=docker

function usage() {
    echo "Usage: ${ME} [Image_Name]"
    exit 1
}

if [ -z "${1}" ]; then
    usage
fi

name=${1}

echo ${tool} run --rm -it ${name} bash
${tool} run --rm -it ${name} bash
