#!/bin/bash
# https://github.com/sammtcbn/dotfiles
# Written by sammtcbn 2018.12.21
function usage()
{
    echo "Usage: $0 [SERVER_IP]"
    echo "    SERVER_IP: assign MQTT Broker ip, default is localhost,"
    echo "               or you can use a test broker test.mosquitto.org"
    exit 0
}

function cmd_exists ()
{
    if ! type $1> /dev/null 2>&1; then
        return 1
    else
        return 0
    fi
}

if ! cmd_exists mosquitto_pub ; then
    echo "mosquitto_pub not found"
    exit 0
fi

SERVER=localhost
TOPIC="hellomqtt/topic"
PAYLOAD="Hello"

if [ ! -z "${1}" ]; then
    SERVER=${1}
fi

mosquitto_pub -h ${SERVER} -t ${TOPIC} -d -m ${PAYLOAD}
if [ $? != 0 ]; then
    usage
fi
