#!/bin/bash
TOPDIR=$(pwd)

REPOALL=(
dotfiles spe git-utils fpjson libreadini logshow sccu advutil ingrautil ediutil mqtt-show-msg mqtt-show-msg-nodejs lineto ssn ssp advdotfiles tsdump.js susi-hello report-sys-info sgcu netplan-apply-daemon device-ss device-demo-plugin-installer nodejs-notes sandbox-utils adv-wsb msys2-favorite-binary influxdb-installer monitor-win-boot sfx_builder nginx-installer grafana-installer solr-installer minio-installer redis-installer win-app-installer wsb-by-chocolatey wsb-by-scoop mongodb-installer microk8s-demo utility-scripts cloudnative-utils minikube-demo nodered-installer multipass-for-microk8s systemd-service-demo python-notes golang-notes elasticsearch-installer ros-notes mariadb-installer ngrok-installer docker-utils app-container-launcher rust-notes pvtmatters linux-app-installer testarea testpvt shell-snippets workpvt vi-installer binary-utility aspeed-cerberus-test aspeed-intelpfr-test aspeed-bmc-image dart-notes cecfw cecimg astzephyrprj
)

function myclone()
{
    local url=$1
    if hash gclone 2> /dev/null; then
        gclone $url
    elif [ -e ~/bin/gclone ]; then
        ~/bin/gclone $url
    else
        git clone $url
    fi
}

function gh() {
    local project=$1
    local url=https://github.com/sammtcbn/${project}.git
    echo "${url} ..."
    myclone ${url}
}

for i in "${REPOALL[@]}";
do
    gh "$i";
done
