#!/bin/bash
# gadd - git add file
# https://github.com/sammtcbn/dotfiles
# Written by sammtcbn 2019.7.26
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [file]"
    exit 1
}

file=${1}

if [ -z "${file}" ]; then
    usage
fi

git add ${file} || exit 1
