#!/bin/bash
# https://github.com/sammtcbn/dotfiles
# Written by sammtcbn 2019.7.17
# To clear git local config
git config --unset user.name || exit 1
git config --unset user.email || exit 1
git config --local user.name || exit 1
git config --local user.email || exit 1
