#!/bin/bash
# gcommit - git commit current repository
# https://github.com/sammtcbn/dotfiles
# Written by sammtcbn 2019.8.6
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [message]"
}

msg=${@}

if [ -z "${msg}" ]; then
    git commit
else
    git commit -m "${msg}"
fi
