#!/bin/bash
# https://github.com/sammtcbn/dotfiles
# Written by sammtcbn 2017.12.14

ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [parameter]"
    exit 1
}

parameter=${1}

if [ -z "${parameter}" ]; then
    usage
fi

git diff ${parameter} || exit 1
