#!/bin/bash
# https://github.com/sammtcbn/dotfiles
# Written by sammtcbn 2017.12.14

ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [commit]"
    exit 1
}

commit=${1}

if [ -z "${1}" ]; then
    usage
fi

git --no-pager diff ${commit}^ ${commit} || exit 1
