#!/bin/bash
# https://github.com/sammtcbn/dotfiles
# Written by sammtcbn 2019.5.30

ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [commit]"
    exit 1
}

commit=${1}

if [ -z "${1}" ]; then
    usage
else
    commit=${1}
fi

git diff ${commit}^ ${commit} || exit 1
