#!/bin/bash
# https://github.com/sammtcbn/dotfiles
# Written by sammtcbn 2017.12.14

parameter=${1}

if [ -z "${parameter}" ]; then
    git diff --name-status || exit 1
else
    git diff --name-status ${parameter} || exit 1
fi
