#!/bin/bash
# https://github.com/sammtcbn/dotfiles
# Written by sammtcbn 2019.7.17

git config user.name "Sam35.Lin" || exit 1
git config user.email "Sam35.Lin@advantech.com.tw" || exit 1
git config --local user.name || exit 1
git config --local user.email || exit 1
