#!/bin/bash
# https://github.com/sammtcbn/dotfiles
# Written by sammtcbn 2019.7.17

git config user.name "sammtcbn" || exit 1
git config user.email "sammtcbn@gmail.com" || exit 1
git config --local user.name || exit 1
git config --local user.email || exit 1
