#!/bin/bash
# https://github.com/sammtcbn/dotfiles
# Written by sammtcbn 2019.7.25

function showmenu() {
    echo "1) git clone spe"
    echo "2) git clone dotfiles"
    echo "3) git clone advutil"
    echo "c) local config - clear"
    echo "d) global config - clear"
    echo "q) quit"
}

showmenu
read -p "Choose: " ins

case "$ins" in
    1)
        git clone https://github.com/sammtcbn/spe.git
        ;;
    2)
        git clone https://github.com/sammtcbn/dotfiles.git
        ;;
    3)
        git clone https://github.com/sammtcbn/advutil.git
        ;;
    c)
        git config --unset user.name
        git config --unset user.email
        git config --local user.name
        git config --local user.email
        ;;
    d)
        git config --global --unset user.name
        git config --global --unset user.email
        git config --global user.name
        git config --global user.email
        ;;
    *)
        exit 0
esac
