#!/bin/bash
# https://github.com/sammtcbn/dotfiles
# Written by sammtcbn 2019.7.23
TOPDIR=$(pwd)

if [ -f .git/config ]; then
    git pull
fi

for D in *
do
    if [ -d "${TOPDIR}/${D}" ]; then
        if [ -f ${TOPDIR}/${D}/.git/config ]; then
            echo ${D}
            cd ${TOPDIR}/${D};git pull
        fi
    fi
done
