#!/bin/bash
# https://github.com/sammtcbn/dotfiles
# Written by sammtcbn 2020.11.16
TOPDIR=$(pwd)

REPOALL=(
dotfiles spe git-utils fpjson libreadini logshow sccu advutil ingrautil ediutil mqtt-show-msg lineto ssn ssp advdotfiles tsdump.js susi-hello report-sys-info
)

function myclone()
{
    url=$1
    if hash gclone 2> /dev/null; then
        gclone $url
    else
        git clone $url
    fi
}

function gh() {
    project=$1
    url=https://github.com/sammtcbn/${project}.git
    echo "${url} ..."
    myclone ${url}
}

for i in "${REPOALL[@]}";
do
    gh "$i";
done
