#!/bin/bash
# https://github.com/sammtcbn/dotfiles
# Written by sammtcbn 2019.8.29
TOPDIR=$(pwd)

ADV_GITLAB_ID=
ADV_GITLAB_PW=
ADV_GITLAB_USE_HTTP=y
ADV_GITLAB_USE_SSH=n

EIOT_GITLAB_ID=
EIOT_GITLAB_PW=
EIOT_GITLAB_USE_HTTP=y
EIOT_GITLAB_USE_SSH=n

ADV_SVN_ID=
ADV_SVN_PW=

function load_advgitlab_account() {
    GITLABAUTHFILE=~/.config/.advgitlab
    if [ -f ${GITLABAUTHFILE} ]; then
        ADV_GITLAB_ID=`cat ${GITLABAUTHFILE} | grep ID= | awk 'BEGIN {FS="="}; {print $2}'`
        ADV_GITLAB_PW=`cat ${GITLABAUTHFILE} | grep PW= | awk 'BEGIN {FS="="}; {print $2}'`
        #echo "ADV_GITLAB_ID = ${ADV_GITLAB_ID}"
        #echo "ADV_GITLAB_PW = ${ADV_GITLAB_PW}"
    fi
}

function load_eiotgitlab_account() {
    EIOTGITLABAUTHFILE=~/.config/.eiotgitlab
    if [ -f ${EIOTGITLABAUTHFILE} ]; then
        EIOT_GITLAB_ID=`cat ${EIOTGITLABAUTHFILE} | grep ID= | awk 'BEGIN {FS="="}; {print $2}'`
        EIOT_GITLAB_PW=`cat ${EIOTGITLABAUTHFILE} | grep PW= | awk 'BEGIN {FS="="}; {print $2}'`
        #echo "EIOT_GITLAB_ID = ${EIOT_GITLAB_ID}"
        #echo "EIOT_GITLAB_PW = ${EIOT_GITLAB_PW}"
    fi
}

function load_advsvn_account() {
    SVNAUTHFILE=~/.config/.advsvn
    if [ -f ${SVNAUTHFILE} ]; then
        ADV_SVN_ID=`cat ${SVNAUTHFILE} | grep ID= | awk 'BEGIN {FS="="}; {print $2}'`
        ADV_SVN_PW=`cat ${SVNAUTHFILE} | grep PW= | awk 'BEGIN {FS="="}; {print $2}'`
        #echo "ADV_SVN_ID = ${ADV_SVN_ID}"
        #echo "ADV_SVN_PW = ${ADV_SVN_PW}"
    fi
}

function git_src() {
    folder=$1
    url=$2
    echo "${url} ..."
    if [ ! -d "${TOPDIR}/${folder}" ]; then
        cd $TOPDIR || exit 1
        git clone $url || exit 1
    else
        cd ${TOPDIR}/${folder} || exit 1
        git pull || exit 1
    fi
}

function advgitlab_src() {
    domain="advgitlab.eastasia.cloudapp.azure.com"
    folder=$1
    url=$2
    echo "${url} ..."
    if [ ! -d "${TOPDIR}/${folder}" ]; then
        cd $TOPDIR || exit 1
        if [ "${ADV_GITLAB_USE_HTTP}" == "y" ]; then
            if [ -n "$ADV_GITLAB_ID" ] && [ -n "$ADV_GITLAB_PW" ]; then
                git clone http://${ADV_GITLAB_ID}:${ADV_GITLAB_PW}@${domain}/${url} || exit 1
            elif [ -n "$ADV_GITLAB_ID" ]; then
                git clone http://${ADV_GITLAB_ID}@${domain}/${url} || exit 1
            else
                git clone http://${domain}/${url} || exit 1
            fi
        elif [ "${ADV_GITLAB_USE_SSH}" == "y" ]; then
            git clone git@${domain}:${url} || exit 1
        fi
    else
        cd ${TOPDIR}/${folder} || exit 1
        git pull || exit 1
    fi
}

function eiotgitlab_src() {
    domain="eiot-gitlab.eastasia.cloudapp.azure.com"
    folder=$1
    url=$2
    echo "${url} ..."
    export GIT_SSL_NO_VERIFY=1
    if [ ! -d "${TOPDIR}/${folder}" ]; then
        cd $TOPDIR || exit 1
        if [ "${EIOT_GITLAB_USE_HTTP}" == "y" ]; then
            if [ -n "$EIOT_GITLAB_ID" ] && [ -n "$EIOT_GITLAB_PW" ]; then
                git clone https://${EIOT_GITLAB_ID}:${EIOT_GITLAB_PW}@${domain}/${url} || exit 1
            elif [ -n "$EIOT_GITLAB_ID" ]; then
                git clone https://${EIOT_GITLAB_ID}@${domain}/${url} || exit 1
            else
                git clone https://${domain}/${url} || exit 1
            fi
        elif [ "${EIOT_GITLAB_USE_SSH}" == "y" ]; then
            git clone git@${domain}:${url} || exit 1
        fi
    else
        cd ${TOPDIR}/${folder} || exit 1
	git pull || exit 1
    fi
}

function advsvn_src() {
    domain="172.20.2.44"
    folder=$1
    url=$2
    echo "${url} ..."
    if [ ! -d "${TOPDIR}/${folder}" ]; then
        cd $TOPDIR || exit 1
        if [ -n "$ADV_SVN_ID" ] && [ -n "$ADV_SVN_PW" ]; then
            svn co --username $ADV_SVN_ID https://${domain}/${url} --password $ADV_SVN_PW || exit 1
        elif [ -n "$ADV_SVN_ID" ]; then
            svn co --username $ADV_SVN_ID https://${domain}/${url} || exit 1
        else
            svn co https://${domain}/${url} || exit 1
        fi
    else
       cd ${TOPDIR}/${folder} || exit 1
       svn up || exit 1
    fi
}

load_advgitlab_account
load_eiotgitlab_account
load_advsvn_account

function g_github() {
  git_src APIGateway   https://github.com/ADVANTECH-Corp/APIGateway.git
  git_src WiseSnail    https://github.com/ADVANTECH-Corp/WiseSnail.git
  git_src agentlite    https://github.com/ADVANTECH-Corp/agentlite.git
}

function g_EI-Connect() {
  advgitlab_src EI-Connect         EI-Connect/EI-Connect.git
  advgitlab_src EI-Connect-CSharp  EI-Connect/EI-Connect-CSharp.git
  advgitlab_src EI-Connect-JNI     EI-Connect/EI-Connect-JNI.git
  advgitlab_src EI-Connect-Node.js EI-Connect/EI-Connect-Node.js.git
  advgitlab_src EI-Connect-Python  EI-Connect/EI-Connect-Python.git
  advgitlab_src EI-Lib             EI-Connect/EI-Lib.git
  advgitlab_src EI-Manifests       EI-Connect/EI-Manifests.git
  advgitlab_src EI-MQTTConnector   EI-Connect/EI-MQTTConnector.git
  advgitlab_src EI-Platform        EI-Connect/EI-Platform.git
  advgitlab_src EI-Predefine       EI-Connect/EI-Predefine.git
  advgitlab_src EI-WISECore        EI-Connect/EI-WISECore.git
}

function g_EdgeSense() {
  advgitlab_src advins_template             EdgeSense/advins_template.git
  advgitlab_src AdvPlatform                 EdgeSense/AdvPlatform.git
  advgitlab_src Alarm_msg_service           EdgeSense/Alarm_msg_service.git
  advgitlab_src device-odbc                 EdgeSense/device-odbc.git
  advgitlab_src device-modbus-master        EdgeSense/device-modbus-master.git
  advgitlab_src device-opcua-client-node.js EdgeSense/device-opcua-client-node.js.git
  advgitlab_src device-poc_link-mgt-node.js EdgeSense/device-poc_link-mgt-node.js.git
  advgitlab_src device-snmp-nms-node.js     EdgeSense/device-snmp-nms-node.js.git
  advgitlab_src EdgeX-WiseAgent-Device      EdgeSense/EdgeX-WiseAgent-Device.git
  advgitlab_src ePack                       EdgeSense/ePack.git
  advgitlab_src Mirai                       EdgeSense/Mirai.git
  advgitlab_src Modbus-Slave                EdgeSense/Modbus-Slave.git
  advgitlab_src MQTTBroker                  EdgeSense/MQTTBroker.git
  advgitlab_src NodeRed_IoTGateway          EdgeSense/NodeRed_IoTGateway.git
  advgitlab_src PluginEditor                EdgeSense/PluginEditor.git
  advgitlab_src poc_battery-app-wpf         EdgeSense/poc_battery-app-wpf.git
  advgitlab_src ReyaxSol                    EdgeSense/ReyaxSol.git
  advgitlab_src Service-SDK                 EdgeSense/Service-SDK.git
  advgitlab_src TowerLight-Sensor           EdgeSense/TowerLight-Sensor.git
  advgitlab_src uartmgr                     EdgeSense/uartmgr.git
  advgitlab_src WAPI                        EdgeSense/WAPI.git
  advgitlab_src service_mgt_win             EdgeSense/service_mgt_win.git
}

function g_EdgeSense-Open() {
  advgitlab_src advlog-node.js    EdgeSense-Open/advlog-node.js.git
  advgitlab_src agentlite-node.js EdgeSense-Open/agentlite-node.js.git
}

function g_EI-PaaS-RMM() {
  advgitlab_src RMM-EI-Agent           EI-PaaS-RMM/RMM-EI-Agent.git
  advgitlab_src RMM-EI-Agent           EI-PaaS-RMM/SouthboundAgent.git
  advgitlab_src RMM-EI-Agent_Installer EI-PaaS-RMM/RMM-EI-Agent_Installer.git
}

function g_EI-PaaS-Plugin() {
  advgitlab_src EdgeX-Plugin          EI-PaaS-Plugin/EdgeX-Plugin.git
  advgitlab_src LocalProvision        EI-PaaS-Plugin/LocalProvision.git
  advgitlab_src RuleEngine_Plugin.git EI-PaaS-Plugin/RuleEngine_Plugin.git
}

function g_SRP-Connect() {
  advgitlab_src SRP-Plugin   SRP-Connect/SRP-Plugin.git
}

function g_WISE-IoT()
{
  advgitlab_src WISE-3610_downlink WISE-IoT/WISE-3610_downlink.git
  advgitlab_src AdvTools           WISE-IoT/AdvTools.git
}

function g_EIOT_GITLAB() {
  eiotgitlab_src wiseagent-ui-electron  ei-paas-rmm/wiseagent-ui-electron.git
}

function g_advsvn() {
  advsvn_src CAgentIoT   svn/SUSIAccess/SA3.1/trunk/Agent/CAgentIoT
  advsvn_src CAgentIoT   svn/SUSIAccess/SA3.1/trunk/Agent/Installer
}

g_github
g_EdgeSense
g_EdgeSense-Open
g_EI-Connect
g_EI-PaaS-RMM
g_EI-PaaS-Plugin
g_SRP-Connect
g_WISE-IoT
g_EIOT_GITLAB
g_advsvn
