#!/bin/bash
# https://github.com/sammtcbn/dotfiles
# Written by sammtcbn 2020.9.30
TOPDIR=$(pwd)

function myclone()
{
    url=$1
    if hash gclone 2> /dev/null; then
        gclone $url
    else
        git clone $url
    fi
}

myclone https://github.com/samba-team/samba.git
myclone https://github.com/warmcat/libwebsockets.git
myclone https://github.com/opencv/opencv.git
myclone https://github.com/torvalds/linux.git
myclone https://github.com/apache/httpd.git
myclone https://github.com/stephane/libmodbus.git
myclone https://github.com/smartmontools/smartmontools.git
myclone https://github.com/nginx/nginx.git
myclone https://github.com/curl/curl.git
myclone https://github.com/madler/zlib.git
myclone https://github.com/eclipse/paho.mqtt.c.git
myclone https://github.com/eclipse/mosquitto.git
myclone https://git.savannah.gnu.org/git/wget.git
